export const get = (locator: string) => cy.get(locator)
export const wrap = (locator: any) => cy.wrap(locator)
export const log = (content: any) => cy.log(JSON.stringify(content))
export const visit = (url: string) => cy.visit(url)
export const click = (locator: any) => get(locator).click()
export const text = (locator: any) => get(locator).invoke('text')
export const type = (locator: any, text: any) => get(locator).type(text)